### ISSUE TITLE
Windows下router prefix的bug

### ISSUE THREAD

**Issue by yueisme** [larkjs/lark-router#23]
[https://github.com/larkjs/lark-router/blob/master/index.js#L59](https://github.com/larkjs/lark-router/blob/master/index.js#L59)
[https://github.com/larkjs/lark-router/blob/master/index.js#L66](https://github.com/larkjs/lark-router/blob/master/index.js#L66)
/.easy/index.js 和 /index.js

path.normalize() 返回的路径适用于文件系统，直接用在route path中会有问题，Windows系统会出现"\\path"的错误格式导致404情况

![err](https://cloud.githubusercontent.com/assets/6147380/15767265/24084c84-2979-11e6-8fe5-9241787e7aaa.jpg)

```javascript
    if (prefix) {
            // replace '\' to '/'
            function fixPath(path){
                return String(path).replace(/\\/g, '/');
            }

            prefix = fixPath(path.normalize(prefix));
            ...
            opts.routePrefix = fixPath(opts.routePrefix);
            ....
            return this;
        }
```

**Comment by zezhou** [comment]
fix in https://github.com/larkjs/lark-router/pull/24
